apiVersion : apps/v1
kind: Deployment
metadata:
  name: app1nginxwithaks 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1nginxwithaks
  template:
    metadata:
      labels:
        app: app1nginxwithaks 
    spec:
      containers:
        - name: app1nginxwithaks 
          image: raiaksregistry.azurecr.io/app1/nginxwithaks
          ports:
          - containerPort: 80
      imagePullSecrets: #this secret is used to pull image while deploying
        - name: raiaksregistry22776778-auth
