apiVersion: v1
kind: Service
metadata:
    name: app1nginxwithaks
spec:
    type: LoadBalancer
    ports:
    - port: 440
      targetPort: 5000
    selector:
        app: app1nginxwithaks
